namespace NeltharionRPGGame.Structure
{
    public enum SpriteType
    {
        Axe,
        Bow,
        Buckler,
        Club,
        Pike,
        PoleArm,
        Potion,
        MageRight,
        MageLeft,
        WitchLeft,
        WitchRight,
        FighterRight,
        FighterLeft,
        TowerShield,
        Stuff,
        Sword,
        DefaultWeapon,
        RedHeart,
        BlackHeart,
        BurningGround,
        HealthPotion,
        AttackPotion,
        DefensePotion
    }
}