namespace NeltharionRPGGame.Data
{
    public enum SpriteType
    {
        None,
        Axe,
        Bow,
        Buckler,
        Club,
        Pike,
        PoleArm,
        Potion,
        MageRight,
        MageLeft,
        WitchLeft,
        WitchRight,
        FighterRight,
        FighterLeft,
        TowerShield,
        Stuff,
        Sword,
        DefaultWeapon,
        RedHeart,
        BlackHeart,
        BurningGround,
        HealthPotion,
        AttackPotion,
        DefensePotion,
        Firebolt,
        Fireball,
        Meteor,
        Icebolt,
        FrostNova,
        GlacialSpike,
        ChargedBolt,
        ShiverArmor,
        DefianceAura
    }
}